//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: pantrytracker.proto

package com.bunnytechsolutions.pantrytracker.models;

@kotlin.jvm.JvmSynthetic
inline fun entry(block: com.bunnytechsolutions.pantrytracker.models.EntryKt.Dsl.() -> kotlin.Unit): com.bunnytechsolutions.pantrytracker.models.Entry =
  com.bunnytechsolutions.pantrytracker.models.EntryKt.Dsl._create(com.bunnytechsolutions.pantrytracker.models.Entry.newBuilder()).apply { block() }._build()
object EntryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.bunnytechsolutions.pantrytracker.models.Entry.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.bunnytechsolutions.pantrytracker.models.Entry.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.bunnytechsolutions.pantrytracker.models.Entry = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string productCode = 2;</code>
     */
    var productCode: kotlin.String
      @JvmName("getProductCode")
      get() = _builder.getProductCode()
      @JvmName("setProductCode")
      set(value) {
        _builder.setProductCode(value)
      }
    /**
     * <code>string productCode = 2;</code>
     */
    fun clearProductCode() {
      _builder.clearProductCode()
    }

    /**
     * <code>int32 portions = 3;</code>
     */
    var portions: kotlin.Int
      @JvmName("getPortions")
      get() = _builder.getPortions()
      @JvmName("setPortions")
      set(value) {
        _builder.setPortions(value)
      }
    /**
     * <code>int32 portions = 3;</code>
     */
    fun clearPortions() {
      _builder.clearPortions()
    }

    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     */
    var expires: com.google.protobuf.Timestamp
      @JvmName("getExpires")
      get() = _builder.getExpires()
      @JvmName("setExpires")
      set(value) {
        _builder.setExpires(value)
      }
    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     */
    fun clearExpires() {
      _builder.clearExpires()
    }
    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     * @return Whether the expires field is set.
     */
    fun hasExpires(): kotlin.Boolean {
      return _builder.hasExpires()
    }

    /**
     * <code>bool reminder = 5;</code>
     */
    var reminder: kotlin.Boolean
      @JvmName("getReminder")
      get() = _builder.getReminder()
      @JvmName("setReminder")
      set(value) {
        _builder.setReminder(value)
      }
    /**
     * <code>bool reminder = 5;</code>
     */
    fun clearReminder() {
      _builder.clearReminder()
    }

    /**
     * <code>bool portionReminder = 6;</code>
     */
    var portionReminder: kotlin.Boolean
      @JvmName("getPortionReminder")
      get() = _builder.getPortionReminder()
      @JvmName("setPortionReminder")
      set(value) {
        _builder.setPortionReminder(value)
      }
    /**
     * <code>bool portionReminder = 6;</code>
     */
    fun clearPortionReminder() {
      _builder.clearPortionReminder()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class ExpirePortionRemindersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
     val expirePortionReminders: com.google.protobuf.kotlin.DslList<com.google.protobuf.Timestamp, ExpirePortionRemindersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getExpirePortionRemindersList()
      )
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     * @param value The expirePortionReminders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addExpirePortionReminders")
    fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Timestamp, ExpirePortionRemindersProxy>.add(value: com.google.protobuf.Timestamp) {
      _builder.addExpirePortionReminders(value)
    }/**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     * @param value The expirePortionReminders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignExpirePortionReminders")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Timestamp, ExpirePortionRemindersProxy>.plusAssign(value: com.google.protobuf.Timestamp) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     * @param values The expirePortionReminders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllExpirePortionReminders")
    fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Timestamp, ExpirePortionRemindersProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Timestamp>) {
      _builder.addAllExpirePortionReminders(values)
    }/**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     * @param values The expirePortionReminders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllExpirePortionReminders")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Timestamp, ExpirePortionRemindersProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Timestamp>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     * @param index The index to set the value at.
     * @param value The expirePortionReminders to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setExpirePortionReminders")
    operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Timestamp, ExpirePortionRemindersProxy>.set(index: kotlin.Int, value: com.google.protobuf.Timestamp) {
      _builder.setExpirePortionReminders(index, value)
    }/**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearExpirePortionReminders")
    fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Timestamp, ExpirePortionRemindersProxy>.clear() {
      _builder.clearExpirePortionReminders()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun com.bunnytechsolutions.pantrytracker.models.Entry.copy(block: com.bunnytechsolutions.pantrytracker.models.EntryKt.Dsl.() -> kotlin.Unit): com.bunnytechsolutions.pantrytracker.models.Entry =
  com.bunnytechsolutions.pantrytracker.models.EntryKt.Dsl._create(this.toBuilder()).apply { block() }._build()
