// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pantrytracker.proto

package com.bunnytechsolutions.pantrytracker.models;

/**
 * <pre>
 * Ensure DB can filter by: id, productID, expires
 * </pre>
 *
 * Protobuf type {@code Entry}
 */
public final class Entry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Entry)
    EntryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Entry.newBuilder() to construct.
  private Entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Entry() {
    id_ = "";
    productCode_ = "";
    expirePortionReminders_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Entry();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Entry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            productCode_ = s;
            break;
          }
          case 24: {

            portions_ = input.readInt32();
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (expires_ != null) {
              subBuilder = expires_.toBuilder();
            }
            expires_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(expires_);
              expires_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            reminder_ = input.readBool();
            break;
          }
          case 48: {

            portionReminder_ = input.readBool();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              expirePortionReminders_ = new java.util.ArrayList<com.google.protobuf.Timestamp>();
              mutable_bitField0_ |= 0x00000001;
            }
            expirePortionReminders_.add(
                input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        expirePortionReminders_ = java.util.Collections.unmodifiableList(expirePortionReminders_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Entry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Entry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bunnytechsolutions.pantrytracker.models.Entry.class, com.bunnytechsolutions.pantrytracker.models.Entry.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object productCode_;
  /**
   * <code>string productCode = 2;</code>
   * @return The productCode.
   */
  @java.lang.Override
  public java.lang.String getProductCode() {
    java.lang.Object ref = productCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productCode_ = s;
      return s;
    }
  }
  /**
   * <code>string productCode = 2;</code>
   * @return The bytes for productCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductCodeBytes() {
    java.lang.Object ref = productCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORTIONS_FIELD_NUMBER = 3;
  private int portions_;
  /**
   * <code>int32 portions = 3;</code>
   * @return The portions.
   */
  @java.lang.Override
  public int getPortions() {
    return portions_;
  }

  public static final int EXPIRES_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp expires_;
  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   * @return Whether the expires field is set.
   */
  @java.lang.Override
  public boolean hasExpires() {
    return expires_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   * @return The expires.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getExpires() {
    return expires_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expires_;
  }
  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getExpiresOrBuilder() {
    return getExpires();
  }

  public static final int REMINDER_FIELD_NUMBER = 5;
  private boolean reminder_;
  /**
   * <code>bool reminder = 5;</code>
   * @return The reminder.
   */
  @java.lang.Override
  public boolean getReminder() {
    return reminder_;
  }

  public static final int PORTIONREMINDER_FIELD_NUMBER = 6;
  private boolean portionReminder_;
  /**
   * <code>bool portionReminder = 6;</code>
   * @return The portionReminder.
   */
  @java.lang.Override
  public boolean getPortionReminder() {
    return portionReminder_;
  }

  public static final int EXPIREPORTIONREMINDERS_FIELD_NUMBER = 7;
  private java.util.List<com.google.protobuf.Timestamp> expirePortionReminders_;
  /**
   * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Timestamp> getExpirePortionRemindersList() {
    return expirePortionReminders_;
  }
  /**
   * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.TimestampOrBuilder> 
      getExpirePortionRemindersOrBuilderList() {
    return expirePortionReminders_;
  }
  /**
   * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
   */
  @java.lang.Override
  public int getExpirePortionRemindersCount() {
    return expirePortionReminders_.size();
  }
  /**
   * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getExpirePortionReminders(int index) {
    return expirePortionReminders_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getExpirePortionRemindersOrBuilder(
      int index) {
    return expirePortionReminders_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productCode_);
    }
    if (portions_ != 0) {
      output.writeInt32(3, portions_);
    }
    if (expires_ != null) {
      output.writeMessage(4, getExpires());
    }
    if (reminder_ != false) {
      output.writeBool(5, reminder_);
    }
    if (portionReminder_ != false) {
      output.writeBool(6, portionReminder_);
    }
    for (int i = 0; i < expirePortionReminders_.size(); i++) {
      output.writeMessage(7, expirePortionReminders_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productCode_);
    }
    if (portions_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, portions_);
    }
    if (expires_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getExpires());
    }
    if (reminder_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, reminder_);
    }
    if (portionReminder_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, portionReminder_);
    }
    for (int i = 0; i < expirePortionReminders_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, expirePortionReminders_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bunnytechsolutions.pantrytracker.models.Entry)) {
      return super.equals(obj);
    }
    com.bunnytechsolutions.pantrytracker.models.Entry other = (com.bunnytechsolutions.pantrytracker.models.Entry) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getProductCode()
        .equals(other.getProductCode())) return false;
    if (getPortions()
        != other.getPortions()) return false;
    if (hasExpires() != other.hasExpires()) return false;
    if (hasExpires()) {
      if (!getExpires()
          .equals(other.getExpires())) return false;
    }
    if (getReminder()
        != other.getReminder()) return false;
    if (getPortionReminder()
        != other.getPortionReminder()) return false;
    if (!getExpirePortionRemindersList()
        .equals(other.getExpirePortionRemindersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + PRODUCTCODE_FIELD_NUMBER;
    hash = (53 * hash) + getProductCode().hashCode();
    hash = (37 * hash) + PORTIONS_FIELD_NUMBER;
    hash = (53 * hash) + getPortions();
    if (hasExpires()) {
      hash = (37 * hash) + EXPIRES_FIELD_NUMBER;
      hash = (53 * hash) + getExpires().hashCode();
    }
    hash = (37 * hash) + REMINDER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReminder());
    hash = (37 * hash) + PORTIONREMINDER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPortionReminder());
    if (getExpirePortionRemindersCount() > 0) {
      hash = (37 * hash) + EXPIREPORTIONREMINDERS_FIELD_NUMBER;
      hash = (53 * hash) + getExpirePortionRemindersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bunnytechsolutions.pantrytracker.models.Entry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Entry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Entry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Entry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Entry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Entry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Entry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Entry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Entry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Entry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Entry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Entry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bunnytechsolutions.pantrytracker.models.Entry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Ensure DB can filter by: id, productID, expires
   * </pre>
   *
   * Protobuf type {@code Entry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Entry)
      com.bunnytechsolutions.pantrytracker.models.EntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Entry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bunnytechsolutions.pantrytracker.models.Entry.class, com.bunnytechsolutions.pantrytracker.models.Entry.Builder.class);
    }

    // Construct using com.bunnytechsolutions.pantrytracker.models.Entry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getExpirePortionRemindersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      productCode_ = "";

      portions_ = 0;

      if (expiresBuilder_ == null) {
        expires_ = null;
      } else {
        expires_ = null;
        expiresBuilder_ = null;
      }
      reminder_ = false;

      portionReminder_ = false;

      if (expirePortionRemindersBuilder_ == null) {
        expirePortionReminders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        expirePortionRemindersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Entry_descriptor;
    }

    @java.lang.Override
    public com.bunnytechsolutions.pantrytracker.models.Entry getDefaultInstanceForType() {
      return com.bunnytechsolutions.pantrytracker.models.Entry.getDefaultInstance();
    }

    @java.lang.Override
    public com.bunnytechsolutions.pantrytracker.models.Entry build() {
      com.bunnytechsolutions.pantrytracker.models.Entry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bunnytechsolutions.pantrytracker.models.Entry buildPartial() {
      com.bunnytechsolutions.pantrytracker.models.Entry result = new com.bunnytechsolutions.pantrytracker.models.Entry(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.productCode_ = productCode_;
      result.portions_ = portions_;
      if (expiresBuilder_ == null) {
        result.expires_ = expires_;
      } else {
        result.expires_ = expiresBuilder_.build();
      }
      result.reminder_ = reminder_;
      result.portionReminder_ = portionReminder_;
      if (expirePortionRemindersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          expirePortionReminders_ = java.util.Collections.unmodifiableList(expirePortionReminders_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.expirePortionReminders_ = expirePortionReminders_;
      } else {
        result.expirePortionReminders_ = expirePortionRemindersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bunnytechsolutions.pantrytracker.models.Entry) {
        return mergeFrom((com.bunnytechsolutions.pantrytracker.models.Entry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bunnytechsolutions.pantrytracker.models.Entry other) {
      if (other == com.bunnytechsolutions.pantrytracker.models.Entry.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getProductCode().isEmpty()) {
        productCode_ = other.productCode_;
        onChanged();
      }
      if (other.getPortions() != 0) {
        setPortions(other.getPortions());
      }
      if (other.hasExpires()) {
        mergeExpires(other.getExpires());
      }
      if (other.getReminder() != false) {
        setReminder(other.getReminder());
      }
      if (other.getPortionReminder() != false) {
        setPortionReminder(other.getPortionReminder());
      }
      if (expirePortionRemindersBuilder_ == null) {
        if (!other.expirePortionReminders_.isEmpty()) {
          if (expirePortionReminders_.isEmpty()) {
            expirePortionReminders_ = other.expirePortionReminders_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureExpirePortionRemindersIsMutable();
            expirePortionReminders_.addAll(other.expirePortionReminders_);
          }
          onChanged();
        }
      } else {
        if (!other.expirePortionReminders_.isEmpty()) {
          if (expirePortionRemindersBuilder_.isEmpty()) {
            expirePortionRemindersBuilder_.dispose();
            expirePortionRemindersBuilder_ = null;
            expirePortionReminders_ = other.expirePortionReminders_;
            bitField0_ = (bitField0_ & ~0x00000001);
            expirePortionRemindersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExpirePortionRemindersFieldBuilder() : null;
          } else {
            expirePortionRemindersBuilder_.addAllMessages(other.expirePortionReminders_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bunnytechsolutions.pantrytracker.models.Entry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bunnytechsolutions.pantrytracker.models.Entry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productCode_ = "";
    /**
     * <code>string productCode = 2;</code>
     * @return The productCode.
     */
    public java.lang.String getProductCode() {
      java.lang.Object ref = productCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productCode = 2;</code>
     * @return The bytes for productCode.
     */
    public com.google.protobuf.ByteString
        getProductCodeBytes() {
      java.lang.Object ref = productCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productCode = 2;</code>
     * @param value The productCode to set.
     * @return This builder for chaining.
     */
    public Builder setProductCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productCode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductCode() {
      
      productCode_ = getDefaultInstance().getProductCode();
      onChanged();
      return this;
    }
    /**
     * <code>string productCode = 2;</code>
     * @param value The bytes for productCode to set.
     * @return This builder for chaining.
     */
    public Builder setProductCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productCode_ = value;
      onChanged();
      return this;
    }

    private int portions_ ;
    /**
     * <code>int32 portions = 3;</code>
     * @return The portions.
     */
    @java.lang.Override
    public int getPortions() {
      return portions_;
    }
    /**
     * <code>int32 portions = 3;</code>
     * @param value The portions to set.
     * @return This builder for chaining.
     */
    public Builder setPortions(int value) {
      
      portions_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 portions = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPortions() {
      
      portions_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp expires_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expiresBuilder_;
    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     * @return Whether the expires field is set.
     */
    public boolean hasExpires() {
      return expiresBuilder_ != null || expires_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     * @return The expires.
     */
    public com.google.protobuf.Timestamp getExpires() {
      if (expiresBuilder_ == null) {
        return expires_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expires_;
      } else {
        return expiresBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     */
    public Builder setExpires(com.google.protobuf.Timestamp value) {
      if (expiresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expires_ = value;
        onChanged();
      } else {
        expiresBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     */
    public Builder setExpires(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expiresBuilder_ == null) {
        expires_ = builderForValue.build();
        onChanged();
      } else {
        expiresBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     */
    public Builder mergeExpires(com.google.protobuf.Timestamp value) {
      if (expiresBuilder_ == null) {
        if (expires_ != null) {
          expires_ =
            com.google.protobuf.Timestamp.newBuilder(expires_).mergeFrom(value).buildPartial();
        } else {
          expires_ = value;
        }
        onChanged();
      } else {
        expiresBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     */
    public Builder clearExpires() {
      if (expiresBuilder_ == null) {
        expires_ = null;
        onChanged();
      } else {
        expires_ = null;
        expiresBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpiresBuilder() {
      
      onChanged();
      return getExpiresFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpiresOrBuilder() {
      if (expiresBuilder_ != null) {
        return expiresBuilder_.getMessageOrBuilder();
      } else {
        return expires_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expires_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getExpiresFieldBuilder() {
      if (expiresBuilder_ == null) {
        expiresBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpires(),
                getParentForChildren(),
                isClean());
        expires_ = null;
      }
      return expiresBuilder_;
    }

    private boolean reminder_ ;
    /**
     * <code>bool reminder = 5;</code>
     * @return The reminder.
     */
    @java.lang.Override
    public boolean getReminder() {
      return reminder_;
    }
    /**
     * <code>bool reminder = 5;</code>
     * @param value The reminder to set.
     * @return This builder for chaining.
     */
    public Builder setReminder(boolean value) {
      
      reminder_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool reminder = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReminder() {
      
      reminder_ = false;
      onChanged();
      return this;
    }

    private boolean portionReminder_ ;
    /**
     * <code>bool portionReminder = 6;</code>
     * @return The portionReminder.
     */
    @java.lang.Override
    public boolean getPortionReminder() {
      return portionReminder_;
    }
    /**
     * <code>bool portionReminder = 6;</code>
     * @param value The portionReminder to set.
     * @return This builder for chaining.
     */
    public Builder setPortionReminder(boolean value) {
      
      portionReminder_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool portionReminder = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPortionReminder() {
      
      portionReminder_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.Timestamp> expirePortionReminders_ =
      java.util.Collections.emptyList();
    private void ensureExpirePortionRemindersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        expirePortionReminders_ = new java.util.ArrayList<com.google.protobuf.Timestamp>(expirePortionReminders_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expirePortionRemindersBuilder_;

    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public java.util.List<com.google.protobuf.Timestamp> getExpirePortionRemindersList() {
      if (expirePortionRemindersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(expirePortionReminders_);
      } else {
        return expirePortionRemindersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public int getExpirePortionRemindersCount() {
      if (expirePortionRemindersBuilder_ == null) {
        return expirePortionReminders_.size();
      } else {
        return expirePortionRemindersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public com.google.protobuf.Timestamp getExpirePortionReminders(int index) {
      if (expirePortionRemindersBuilder_ == null) {
        return expirePortionReminders_.get(index);
      } else {
        return expirePortionRemindersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public Builder setExpirePortionReminders(
        int index, com.google.protobuf.Timestamp value) {
      if (expirePortionRemindersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExpirePortionRemindersIsMutable();
        expirePortionReminders_.set(index, value);
        onChanged();
      } else {
        expirePortionRemindersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public Builder setExpirePortionReminders(
        int index, com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expirePortionRemindersBuilder_ == null) {
        ensureExpirePortionRemindersIsMutable();
        expirePortionReminders_.set(index, builderForValue.build());
        onChanged();
      } else {
        expirePortionRemindersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public Builder addExpirePortionReminders(com.google.protobuf.Timestamp value) {
      if (expirePortionRemindersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExpirePortionRemindersIsMutable();
        expirePortionReminders_.add(value);
        onChanged();
      } else {
        expirePortionRemindersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public Builder addExpirePortionReminders(
        int index, com.google.protobuf.Timestamp value) {
      if (expirePortionRemindersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExpirePortionRemindersIsMutable();
        expirePortionReminders_.add(index, value);
        onChanged();
      } else {
        expirePortionRemindersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public Builder addExpirePortionReminders(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expirePortionRemindersBuilder_ == null) {
        ensureExpirePortionRemindersIsMutable();
        expirePortionReminders_.add(builderForValue.build());
        onChanged();
      } else {
        expirePortionRemindersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public Builder addExpirePortionReminders(
        int index, com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expirePortionRemindersBuilder_ == null) {
        ensureExpirePortionRemindersIsMutable();
        expirePortionReminders_.add(index, builderForValue.build());
        onChanged();
      } else {
        expirePortionRemindersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public Builder addAllExpirePortionReminders(
        java.lang.Iterable<? extends com.google.protobuf.Timestamp> values) {
      if (expirePortionRemindersBuilder_ == null) {
        ensureExpirePortionRemindersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, expirePortionReminders_);
        onChanged();
      } else {
        expirePortionRemindersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public Builder clearExpirePortionReminders() {
      if (expirePortionRemindersBuilder_ == null) {
        expirePortionReminders_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        expirePortionRemindersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public Builder removeExpirePortionReminders(int index) {
      if (expirePortionRemindersBuilder_ == null) {
        ensureExpirePortionRemindersIsMutable();
        expirePortionReminders_.remove(index);
        onChanged();
      } else {
        expirePortionRemindersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpirePortionRemindersBuilder(
        int index) {
      return getExpirePortionRemindersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpirePortionRemindersOrBuilder(
        int index) {
      if (expirePortionRemindersBuilder_ == null) {
        return expirePortionReminders_.get(index);  } else {
        return expirePortionRemindersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public java.util.List<? extends com.google.protobuf.TimestampOrBuilder> 
         getExpirePortionRemindersOrBuilderList() {
      if (expirePortionRemindersBuilder_ != null) {
        return expirePortionRemindersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(expirePortionReminders_);
      }
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder addExpirePortionRemindersBuilder() {
      return getExpirePortionRemindersFieldBuilder().addBuilder(
          com.google.protobuf.Timestamp.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder addExpirePortionRemindersBuilder(
        int index) {
      return getExpirePortionRemindersFieldBuilder().addBuilder(
          index, com.google.protobuf.Timestamp.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
     */
    public java.util.List<com.google.protobuf.Timestamp.Builder> 
         getExpirePortionRemindersBuilderList() {
      return getExpirePortionRemindersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getExpirePortionRemindersFieldBuilder() {
      if (expirePortionRemindersBuilder_ == null) {
        expirePortionRemindersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                expirePortionReminders_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        expirePortionReminders_ = null;
      }
      return expirePortionRemindersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Entry)
  }

  // @@protoc_insertion_point(class_scope:Entry)
  private static final com.bunnytechsolutions.pantrytracker.models.Entry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bunnytechsolutions.pantrytracker.models.Entry();
  }

  public static com.bunnytechsolutions.pantrytracker.models.Entry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Entry>
      PARSER = new com.google.protobuf.AbstractParser<Entry>() {
    @java.lang.Override
    public Entry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Entry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Entry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Entry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bunnytechsolutions.pantrytracker.models.Entry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

