// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pantrytracker.proto

package com.bunnytechsolutions.pantrytracker.models;

public interface EntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Entry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string productID = 2;</code>
   * @return The productID.
   */
  java.lang.String getProductID();
  /**
   * <code>string productID = 2;</code>
   * @return The bytes for productID.
   */
  com.google.protobuf.ByteString
      getProductIDBytes();

  /**
   * <code>int32 portions = 3;</code>
   * @return The portions.
   */
  int getPortions();

  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   * @return Whether the expires field is set.
   */
  boolean hasExpires();
  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   * @return The expires.
   */
  com.google.protobuf.Timestamp getExpires();
  /**
   * <code>.google.protobuf.Timestamp expires = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiresOrBuilder();

  /**
   * <code>bool reminder = 5;</code>
   * @return The reminder.
   */
  boolean getReminder();

  /**
   * <code>bool portionReminder = 6;</code>
   * @return The portionReminder.
   */
  boolean getPortionReminder();

  /**
   * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
   */
  java.util.List<com.google.protobuf.Timestamp> 
      getExpirePortionRemindersList();
  /**
   * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
   */
  com.google.protobuf.Timestamp getExpirePortionReminders(int index);
  /**
   * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
   */
  int getExpirePortionRemindersCount();
  /**
   * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
   */
  java.util.List<? extends com.google.protobuf.TimestampOrBuilder> 
      getExpirePortionRemindersOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Timestamp expirePortionReminders = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpirePortionRemindersOrBuilder(
      int index);
}
