// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pantrytracker.proto

package com.bunnytechsolutions.pantrytracker.models;

public interface PantryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Pantry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Entries as list of entryId
   * </pre>
   *
   * <code>repeated string entries = 10;</code>
   * @return A list containing the entries.
   */
  java.util.List<java.lang.String>
      getEntriesList();
  /**
   * <pre>
   * Entries as list of entryId
   * </pre>
   *
   * <code>repeated string entries = 10;</code>
   * @return The count of entries.
   */
  int getEntriesCount();
  /**
   * <pre>
   * Entries as list of entryId
   * </pre>
   *
   * <code>repeated string entries = 10;</code>
   * @param index The index of the element to return.
   * @return The entries at the given index.
   */
  java.lang.String getEntries(int index);
  /**
   * <pre>
   * Entries as list of entryId
   * </pre>
   *
   * <code>repeated string entries = 10;</code>
   * @param index The index of the value to return.
   * @return The bytes of the entries at the given index.
   */
  com.google.protobuf.ByteString
      getEntriesBytes(int index);
}
