// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pantrytracker.proto

package com.bunnytechsolutions.pantrytracker.models;

/**
 * <pre>
 * Ensure DB can filter by: id, name
 * </pre>
 *
 * Protobuf type {@code Pantry}
 */
public final class Pantry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Pantry)
    PantryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Pantry.newBuilder() to construct.
  private Pantry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Pantry() {
    id_ = "";
    name_ = "";
    entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Pantry();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Pantry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              entries_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            entries_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        entries_ = entries_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Pantry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Pantry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bunnytechsolutions.pantrytracker.models.Pantry.class, com.bunnytechsolutions.pantrytracker.models.Pantry.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTRIES_FIELD_NUMBER = 10;
  private com.google.protobuf.LazyStringList entries_;
  /**
   * <pre>
   * Entries as list of entryId
   * </pre>
   *
   * <code>repeated string entries = 10;</code>
   * @return A list containing the entries.
   */
  public com.google.protobuf.ProtocolStringList
      getEntriesList() {
    return entries_;
  }
  /**
   * <pre>
   * Entries as list of entryId
   * </pre>
   *
   * <code>repeated string entries = 10;</code>
   * @return The count of entries.
   */
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <pre>
   * Entries as list of entryId
   * </pre>
   *
   * <code>repeated string entries = 10;</code>
   * @param index The index of the element to return.
   * @return The entries at the given index.
   */
  public java.lang.String getEntries(int index) {
    return entries_.get(index);
  }
  /**
   * <pre>
   * Entries as list of entryId
   * </pre>
   *
   * <code>repeated string entries = 10;</code>
   * @param index The index of the value to return.
   * @return The bytes of the entries at the given index.
   */
  public com.google.protobuf.ByteString
      getEntriesBytes(int index) {
    return entries_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    for (int i = 0; i < entries_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, entries_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < entries_.size(); i++) {
        dataSize += computeStringSizeNoTag(entries_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEntriesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bunnytechsolutions.pantrytracker.models.Pantry)) {
      return super.equals(obj);
    }
    com.bunnytechsolutions.pantrytracker.models.Pantry other = (com.bunnytechsolutions.pantrytracker.models.Pantry) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getEntriesList()
        .equals(other.getEntriesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getEntriesCount() > 0) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntriesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Pantry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bunnytechsolutions.pantrytracker.models.Pantry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Ensure DB can filter by: id, name
   * </pre>
   *
   * Protobuf type {@code Pantry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Pantry)
      com.bunnytechsolutions.pantrytracker.models.PantryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Pantry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Pantry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bunnytechsolutions.pantrytracker.models.Pantry.class, com.bunnytechsolutions.pantrytracker.models.Pantry.Builder.class);
    }

    // Construct using com.bunnytechsolutions.pantrytracker.models.Pantry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Pantry_descriptor;
    }

    @java.lang.Override
    public com.bunnytechsolutions.pantrytracker.models.Pantry getDefaultInstanceForType() {
      return com.bunnytechsolutions.pantrytracker.models.Pantry.getDefaultInstance();
    }

    @java.lang.Override
    public com.bunnytechsolutions.pantrytracker.models.Pantry build() {
      com.bunnytechsolutions.pantrytracker.models.Pantry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bunnytechsolutions.pantrytracker.models.Pantry buildPartial() {
      com.bunnytechsolutions.pantrytracker.models.Pantry result = new com.bunnytechsolutions.pantrytracker.models.Pantry(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.name_ = name_;
      if (((bitField0_ & 0x00000001) != 0)) {
        entries_ = entries_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.entries_ = entries_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bunnytechsolutions.pantrytracker.models.Pantry) {
        return mergeFrom((com.bunnytechsolutions.pantrytracker.models.Pantry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bunnytechsolutions.pantrytracker.models.Pantry other) {
      if (other == com.bunnytechsolutions.pantrytracker.models.Pantry.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.entries_.isEmpty()) {
        if (entries_.isEmpty()) {
          entries_ = other.entries_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureEntriesIsMutable();
          entries_.addAll(other.entries_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bunnytechsolutions.pantrytracker.models.Pantry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bunnytechsolutions.pantrytracker.models.Pantry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEntriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        entries_ = new com.google.protobuf.LazyStringArrayList(entries_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @return A list containing the entries.
     */
    public com.google.protobuf.ProtocolStringList
        getEntriesList() {
      return entries_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @return The count of entries.
     */
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @param index The index of the element to return.
     * @return The entries at the given index.
     */
    public java.lang.String getEntries(int index) {
      return entries_.get(index);
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @param index The index of the value to return.
     * @return The bytes of the entries at the given index.
     */
    public com.google.protobuf.ByteString
        getEntriesBytes(int index) {
      return entries_.getByteString(index);
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @param index The index to set the value at.
     * @param value The entries to set.
     * @return This builder for chaining.
     */
    public Builder setEntries(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEntriesIsMutable();
      entries_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @param value The entries to add.
     * @return This builder for chaining.
     */
    public Builder addEntries(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEntriesIsMutable();
      entries_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @param values The entries to add.
     * @return This builder for chaining.
     */
    public Builder addAllEntries(
        java.lang.Iterable<java.lang.String> values) {
      ensureEntriesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, entries_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntries() {
      entries_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @param value The bytes of the entries to add.
     * @return This builder for chaining.
     */
    public Builder addEntriesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEntriesIsMutable();
      entries_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Pantry)
  }

  // @@protoc_insertion_point(class_scope:Pantry)
  private static final com.bunnytechsolutions.pantrytracker.models.Pantry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bunnytechsolutions.pantrytracker.models.Pantry();
  }

  public static com.bunnytechsolutions.pantrytracker.models.Pantry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Pantry>
      PARSER = new com.google.protobuf.AbstractParser<Pantry>() {
    @java.lang.Override
    public Pantry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Pantry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Pantry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Pantry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bunnytechsolutions.pantrytracker.models.Pantry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

