//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: pantrytracker.proto

package com.bunnytechsolutions.pantrytracker.models;

@kotlin.jvm.JvmSynthetic
inline fun pantry(block: com.bunnytechsolutions.pantrytracker.models.PantryKt.Dsl.() -> kotlin.Unit): com.bunnytechsolutions.pantrytracker.models.Pantry =
  com.bunnytechsolutions.pantrytracker.models.PantryKt.Dsl._create(com.bunnytechsolutions.pantrytracker.models.Pantry.newBuilder()).apply { block() }._build()
object PantryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.bunnytechsolutions.pantrytracker.models.Pantry.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.bunnytechsolutions.pantrytracker.models.Pantry.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.bunnytechsolutions.pantrytracker.models.Pantry = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string name = 2;</code>
     */
    var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 2;</code>
     */
    fun clearName() {
      _builder.clearName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class EntriesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @return A list containing the entries.
     */
    val entries: com.google.protobuf.kotlin.DslList<kotlin.String, EntriesProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEntriesList()
      )
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @param value The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEntries")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, EntriesProxy>.add(value: kotlin.String) {
      _builder.addEntries(value)
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @param value The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEntries")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EntriesProxy>.plusAssign(value: kotlin.String) {
      _builder.addEntries(value)
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @param values The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEntries")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, EntriesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllEntries(values)
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @param values The entries to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEntries")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EntriesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllEntries(values)
    }
    /**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     * @param index The index to set the value at.
     * @param value The entries to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEntries")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, EntriesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setEntries(index, value)
    }/**
     * <pre>
     * Entries as list of entryId
     * </pre>
     *
     * <code>repeated string entries = 10;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEntries")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, EntriesProxy>.clear() {
      _builder.clearEntries()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun com.bunnytechsolutions.pantrytracker.models.Pantry.copy(block: com.bunnytechsolutions.pantrytracker.models.PantryKt.Dsl.() -> kotlin.Unit): com.bunnytechsolutions.pantrytracker.models.Pantry =
  com.bunnytechsolutions.pantrytracker.models.PantryKt.Dsl._create(this.toBuilder()).apply { block() }._build()
