// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pantrytracker.proto

package com.bunnytechsolutions.pantrytracker.models;

/**
 * <pre>
 * Ensure DB can filter by: barcode, name, brand
 * </pre>
 *
 * Protobuf type {@code Product}
 */
public final class Product extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Product)
    ProductOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Product.newBuilder() to construct.
  private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Product() {
    barcode_ = "";
    brand_ = "";
    name_ = "";
    ingredients_ = "";
    nutritionFacts_ = "";
    images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Product();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Product(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            barcode_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            brand_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            ingredients_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            nutritionFacts_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              images_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            images_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        images_ = images_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Product_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Product_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bunnytechsolutions.pantrytracker.models.Product.class, com.bunnytechsolutions.pantrytracker.models.Product.Builder.class);
  }

  public static final int BARCODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object barcode_;
  /**
   * <code>string barcode = 1;</code>
   * @return The barcode.
   */
  @java.lang.Override
  public java.lang.String getBarcode() {
    java.lang.Object ref = barcode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      barcode_ = s;
      return s;
    }
  }
  /**
   * <code>string barcode = 1;</code>
   * @return The bytes for barcode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBarcodeBytes() {
    java.lang.Object ref = barcode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      barcode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BRAND_FIELD_NUMBER = 2;
  private volatile java.lang.Object brand_;
  /**
   * <code>string brand = 2;</code>
   * @return The brand.
   */
  @java.lang.Override
  public java.lang.String getBrand() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      brand_ = s;
      return s;
    }
  }
  /**
   * <code>string brand = 2;</code>
   * @return The bytes for brand.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBrandBytes() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      brand_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INGREDIENTS_FIELD_NUMBER = 4;
  private volatile java.lang.Object ingredients_;
  /**
   * <code>string ingredients = 4;</code>
   * @return The ingredients.
   */
  @java.lang.Override
  public java.lang.String getIngredients() {
    java.lang.Object ref = ingredients_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ingredients_ = s;
      return s;
    }
  }
  /**
   * <code>string ingredients = 4;</code>
   * @return The bytes for ingredients.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIngredientsBytes() {
    java.lang.Object ref = ingredients_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ingredients_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUTRITIONFACTS_FIELD_NUMBER = 5;
  private volatile java.lang.Object nutritionFacts_;
  /**
   * <code>string nutritionFacts = 5;</code>
   * @return The nutritionFacts.
   */
  @java.lang.Override
  public java.lang.String getNutritionFacts() {
    java.lang.Object ref = nutritionFacts_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nutritionFacts_ = s;
      return s;
    }
  }
  /**
   * <code>string nutritionFacts = 5;</code>
   * @return The bytes for nutritionFacts.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNutritionFactsBytes() {
    java.lang.Object ref = nutritionFacts_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nutritionFacts_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGES_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList images_;
  /**
   * <code>repeated string images = 6;</code>
   * @return A list containing the images.
   */
  public com.google.protobuf.ProtocolStringList
      getImagesList() {
    return images_;
  }
  /**
   * <code>repeated string images = 6;</code>
   * @return The count of images.
   */
  public int getImagesCount() {
    return images_.size();
  }
  /**
   * <code>repeated string images = 6;</code>
   * @param index The index of the element to return.
   * @return The images at the given index.
   */
  public java.lang.String getImages(int index) {
    return images_.get(index);
  }
  /**
   * <code>repeated string images = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the images at the given index.
   */
  public com.google.protobuf.ByteString
      getImagesBytes(int index) {
    return images_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(barcode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, barcode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brand_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, brand_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ingredients_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ingredients_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nutritionFacts_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nutritionFacts_);
    }
    for (int i = 0; i < images_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, images_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(barcode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, barcode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brand_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, brand_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ingredients_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ingredients_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nutritionFacts_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nutritionFacts_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < images_.size(); i++) {
        dataSize += computeStringSizeNoTag(images_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getImagesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bunnytechsolutions.pantrytracker.models.Product)) {
      return super.equals(obj);
    }
    com.bunnytechsolutions.pantrytracker.models.Product other = (com.bunnytechsolutions.pantrytracker.models.Product) obj;

    if (!getBarcode()
        .equals(other.getBarcode())) return false;
    if (!getBrand()
        .equals(other.getBrand())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getIngredients()
        .equals(other.getIngredients())) return false;
    if (!getNutritionFacts()
        .equals(other.getNutritionFacts())) return false;
    if (!getImagesList()
        .equals(other.getImagesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BARCODE_FIELD_NUMBER;
    hash = (53 * hash) + getBarcode().hashCode();
    hash = (37 * hash) + BRAND_FIELD_NUMBER;
    hash = (53 * hash) + getBrand().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + INGREDIENTS_FIELD_NUMBER;
    hash = (53 * hash) + getIngredients().hashCode();
    hash = (37 * hash) + NUTRITIONFACTS_FIELD_NUMBER;
    hash = (53 * hash) + getNutritionFacts().hashCode();
    if (getImagesCount() > 0) {
      hash = (37 * hash) + IMAGES_FIELD_NUMBER;
      hash = (53 * hash) + getImagesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bunnytechsolutions.pantrytracker.models.Product parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Product parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Product parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Product parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Product parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Product parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Product parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Product parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Product parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Product parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Product parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bunnytechsolutions.pantrytracker.models.Product parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bunnytechsolutions.pantrytracker.models.Product prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Ensure DB can filter by: barcode, name, brand
   * </pre>
   *
   * Protobuf type {@code Product}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Product)
      com.bunnytechsolutions.pantrytracker.models.ProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bunnytechsolutions.pantrytracker.models.Product.class, com.bunnytechsolutions.pantrytracker.models.Product.Builder.class);
    }

    // Construct using com.bunnytechsolutions.pantrytracker.models.Product.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      barcode_ = "";

      brand_ = "";

      name_ = "";

      ingredients_ = "";

      nutritionFacts_ = "";

      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bunnytechsolutions.pantrytracker.models.PantryTrackerModels.internal_static_Product_descriptor;
    }

    @java.lang.Override
    public com.bunnytechsolutions.pantrytracker.models.Product getDefaultInstanceForType() {
      return com.bunnytechsolutions.pantrytracker.models.Product.getDefaultInstance();
    }

    @java.lang.Override
    public com.bunnytechsolutions.pantrytracker.models.Product build() {
      com.bunnytechsolutions.pantrytracker.models.Product result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bunnytechsolutions.pantrytracker.models.Product buildPartial() {
      com.bunnytechsolutions.pantrytracker.models.Product result = new com.bunnytechsolutions.pantrytracker.models.Product(this);
      int from_bitField0_ = bitField0_;
      result.barcode_ = barcode_;
      result.brand_ = brand_;
      result.name_ = name_;
      result.ingredients_ = ingredients_;
      result.nutritionFacts_ = nutritionFacts_;
      if (((bitField0_ & 0x00000001) != 0)) {
        images_ = images_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.images_ = images_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bunnytechsolutions.pantrytracker.models.Product) {
        return mergeFrom((com.bunnytechsolutions.pantrytracker.models.Product)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bunnytechsolutions.pantrytracker.models.Product other) {
      if (other == com.bunnytechsolutions.pantrytracker.models.Product.getDefaultInstance()) return this;
      if (!other.getBarcode().isEmpty()) {
        barcode_ = other.barcode_;
        onChanged();
      }
      if (!other.getBrand().isEmpty()) {
        brand_ = other.brand_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getIngredients().isEmpty()) {
        ingredients_ = other.ingredients_;
        onChanged();
      }
      if (!other.getNutritionFacts().isEmpty()) {
        nutritionFacts_ = other.nutritionFacts_;
        onChanged();
      }
      if (!other.images_.isEmpty()) {
        if (images_.isEmpty()) {
          images_ = other.images_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureImagesIsMutable();
          images_.addAll(other.images_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bunnytechsolutions.pantrytracker.models.Product parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bunnytechsolutions.pantrytracker.models.Product) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object barcode_ = "";
    /**
     * <code>string barcode = 1;</code>
     * @return The barcode.
     */
    public java.lang.String getBarcode() {
      java.lang.Object ref = barcode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        barcode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string barcode = 1;</code>
     * @return The bytes for barcode.
     */
    public com.google.protobuf.ByteString
        getBarcodeBytes() {
      java.lang.Object ref = barcode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        barcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string barcode = 1;</code>
     * @param value The barcode to set.
     * @return This builder for chaining.
     */
    public Builder setBarcode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      barcode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string barcode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBarcode() {
      
      barcode_ = getDefaultInstance().getBarcode();
      onChanged();
      return this;
    }
    /**
     * <code>string barcode = 1;</code>
     * @param value The bytes for barcode to set.
     * @return This builder for chaining.
     */
    public Builder setBarcodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      barcode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object brand_ = "";
    /**
     * <code>string brand = 2;</code>
     * @return The brand.
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string brand = 2;</code>
     * @return The bytes for brand.
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string brand = 2;</code>
     * @param value The brand to set.
     * @return This builder for chaining.
     */
    public Builder setBrand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      brand_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string brand = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrand() {
      
      brand_ = getDefaultInstance().getBrand();
      onChanged();
      return this;
    }
    /**
     * <code>string brand = 2;</code>
     * @param value The bytes for brand to set.
     * @return This builder for chaining.
     */
    public Builder setBrandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      brand_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ingredients_ = "";
    /**
     * <code>string ingredients = 4;</code>
     * @return The ingredients.
     */
    public java.lang.String getIngredients() {
      java.lang.Object ref = ingredients_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ingredients_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ingredients = 4;</code>
     * @return The bytes for ingredients.
     */
    public com.google.protobuf.ByteString
        getIngredientsBytes() {
      java.lang.Object ref = ingredients_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ingredients_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ingredients = 4;</code>
     * @param value The ingredients to set.
     * @return This builder for chaining.
     */
    public Builder setIngredients(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ingredients_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ingredients = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIngredients() {
      
      ingredients_ = getDefaultInstance().getIngredients();
      onChanged();
      return this;
    }
    /**
     * <code>string ingredients = 4;</code>
     * @param value The bytes for ingredients to set.
     * @return This builder for chaining.
     */
    public Builder setIngredientsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ingredients_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nutritionFacts_ = "";
    /**
     * <code>string nutritionFacts = 5;</code>
     * @return The nutritionFacts.
     */
    public java.lang.String getNutritionFacts() {
      java.lang.Object ref = nutritionFacts_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nutritionFacts_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nutritionFacts = 5;</code>
     * @return The bytes for nutritionFacts.
     */
    public com.google.protobuf.ByteString
        getNutritionFactsBytes() {
      java.lang.Object ref = nutritionFacts_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nutritionFacts_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nutritionFacts = 5;</code>
     * @param value The nutritionFacts to set.
     * @return This builder for chaining.
     */
    public Builder setNutritionFacts(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nutritionFacts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nutritionFacts = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNutritionFacts() {
      
      nutritionFacts_ = getDefaultInstance().getNutritionFacts();
      onChanged();
      return this;
    }
    /**
     * <code>string nutritionFacts = 5;</code>
     * @param value The bytes for nutritionFacts to set.
     * @return This builder for chaining.
     */
    public Builder setNutritionFactsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nutritionFacts_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureImagesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        images_ = new com.google.protobuf.LazyStringArrayList(images_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string images = 6;</code>
     * @return A list containing the images.
     */
    public com.google.protobuf.ProtocolStringList
        getImagesList() {
      return images_.getUnmodifiableView();
    }
    /**
     * <code>repeated string images = 6;</code>
     * @return The count of images.
     */
    public int getImagesCount() {
      return images_.size();
    }
    /**
     * <code>repeated string images = 6;</code>
     * @param index The index of the element to return.
     * @return The images at the given index.
     */
    public java.lang.String getImages(int index) {
      return images_.get(index);
    }
    /**
     * <code>repeated string images = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the images at the given index.
     */
    public com.google.protobuf.ByteString
        getImagesBytes(int index) {
      return images_.getByteString(index);
    }
    /**
     * <code>repeated string images = 6;</code>
     * @param index The index to set the value at.
     * @param value The images to set.
     * @return This builder for chaining.
     */
    public Builder setImages(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
      images_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string images = 6;</code>
     * @param value The images to add.
     * @return This builder for chaining.
     */
    public Builder addImages(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureImagesIsMutable();
      images_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string images = 6;</code>
     * @param values The images to add.
     * @return This builder for chaining.
     */
    public Builder addAllImages(
        java.lang.Iterable<java.lang.String> values) {
      ensureImagesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, images_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string images = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearImages() {
      images_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string images = 6;</code>
     * @param value The bytes of the images to add.
     * @return This builder for chaining.
     */
    public Builder addImagesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureImagesIsMutable();
      images_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Product)
  }

  // @@protoc_insertion_point(class_scope:Product)
  private static final com.bunnytechsolutions.pantrytracker.models.Product DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bunnytechsolutions.pantrytracker.models.Product();
  }

  public static com.bunnytechsolutions.pantrytracker.models.Product getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Product>
      PARSER = new com.google.protobuf.AbstractParser<Product>() {
    @java.lang.Override
    public Product parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Product(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Product> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Product> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bunnytechsolutions.pantrytracker.models.Product getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

